hw2/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('questions/', include('questions.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/questions/')),
]

hw2/mysite/questions/urls.py
from django.urls import path

from . import views

app_name = 'questions'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/answer/', views.answer, name='answer'),
    path('/question/', views.question, name='question'),
]
 

hw2/mysite/questions/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.answer_text

hw2/mysite/questions/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.utils import timezone
from .models import Question, Answer
from django.urls import reverse

def index(request):
    question_list = Question.objects.order_by('-pub_date')
    context = {'question_list': question_list}
    return render(request, 'questions/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'questions/detail.html', {'question': question})

def question(request):
    text = request.POST['question']
    if len(text) > 0:
        question = Question(question_text=text, pub_date=timezone.now())
        question.save()
    return HttpResponseRedirect(reverse('questions:index'))

def answer(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    text = request.POST['answer']
    if len(text) > 0:
        answer = Answer(question=question, answer_text=text, pub_date=timezone.now())
        answer.save()
    return HttpResponseRedirect(reverse('questions:detail', args=(question.id,)))
    

hw2/mysite/questions/templates/questions/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'questions/style.css' %}">

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'questions:answer' question.id %}" method="post">
{% csrf_token %}
    <input type="text" name="answer">
<input type="submit" value="Send answer">
</form>

<ul>
{% for answer in question.answer_set.all %}
    <li>{{ answer.answer_text }}</li>
{% endfor %}
</ul>

hw2/mysite/questions/templates/questions/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'questions/style.css' %}">


<form action="{% url 'questions:question' %}" method="post">
{% csrf_token %}
    <input type="text" name="question">
<input type="submit" value="New question">
</form>

{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'questions:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No questions are available.</p>
{% endif %}